Repository FES10-12-2/vanilla-project, pull requests merged in 2024-07, with the labels that each got.

#12 Feat: 콘솔 로그
  psy.js
Labels: 🛠️기능구현

#13 feat: 회원가입 버튼 구현
  src/hyeji.js
Labels: 🛠️기능구현

#14 feat: try
  index.html
Labels: 🛠️기능구현

#19 feat: 헤더구현
  index.html
Labels: 🛠️기능구현

#20 feat: 충돌
  index.html
Labels: bug

#21 Docs: 문서 내용 수정
  index.html
Labels: documentation

#22 feat/crash/D
  index.html
Labels: 🛠️기능구현
